# Generated by Django 5.0 on 2024-01-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_customuser_fname_alter_customuser_lname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fname',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lname',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
