# Generated by Django 5.0 on 2024-01-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_customuser_fname_alter_customuser_lname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
