# Generated by Django 5.0 on 2024-01-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_customuser_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_public',
            field=models.BooleanField(),
        ),
    ]
