# Generated by Django 5.0 on 2024-01-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_uploadedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='user',
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='uploaded_files/'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='year_published',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
